### ISSUE TITLE
History settings getting lost

### ISSUE THREAD

**Issue by Cumulus7** [t4qjXH8N/ioBroker.wiffi-wz#13]
Hi,

i have a lot of history settings activated. However some of them get turned off every few days.
Do you by any chance manage these settings in your adapter? 
Create the states anew and reset these settings?

![image](https://user-images.githubusercontent.com/45620107/57567554-543fa500-73db-11e9-862c-6d6f5b163e01.png)

All my other history settings in the other adapters i use never showed this behaviour.

![image](https://user-images.githubusercontent.com/45620107/57567563-805b2600-73db-11e9-962a-4e7222dd52f2.png)

Any chance that the "create states for wiffi" might affect the history settings?

THX for your help and greetings,
Markus

**Comment by t4qjXH8N** [comment]
Hey Markus,
please set logging to "debug" and send me the log after the history got lost.

**Comment by t4qjXH8N** [comment]
Sorry, it is already set to debug. Are there any "created state XXX" messages in the log after the history got lost?

**Comment by Cumulus7** [comment]
Hi Christian,
i always have these "create states for wiffi" messages along with every received JSON data.

i think i found the exact moment where the problem arises:
![image](https://user-images.githubusercontent.com/45620107/57574910-43297f00-7441-11e9-82b4-9f0d7752ee18.png)

The same happens again a few seconds later.
See log-file:

[log_20190511.txt](https://github.com/t4qjXH8N/ioBroker.wiffi-wz/files/3169473/log_20190511.txt)

Greetings,
Markus

**Comment by t4qjXH8N** [comment]
What is your js-controller version?

**Comment by Cumulus7** [comment]
![image](https://user-images.githubusercontent.com/45620107/57580175-7fdb9180-74a6-11e9-9992-ef12934a445d.png)
![image](https://user-images.githubusercontent.com/45620107/57580176-91bd3480-74a6-11e9-9184-814a2cd95680.png)

**Comment by t4qjXH8N** [comment]
Hm, I am using the History adapter for logging (not the SQL-logger) and I the history is NOT getting lost. I am also using the same js-controller version. Sorry, I have no possibilty to check SQL logging at the moment.

**Comment by Cumulus7** [comment]
Do you have any idea why the states are created again?
Or why they get "lost" in the first place?

I guess that is the reason why the logging is getting disabled.

**Comment by t4qjXH8N** [comment]
It says states are created, but in fact they are only created if they do not exists. Could you please switch to the history adapter for testing purposes only?

**Comment by Cumulus7** [comment]
Already did that yesterday evening. I will report back when the problem arises again.

**Comment by Cumulus7** [comment]
Hi,

can you take a look again at the log-file i posted?

The JSON received by the adapter at 
>2019-05-11 03:17:27.002  - [34mdebug[39m: wiffi-wz.0 Received JSON data from Wiffi. Full message: {"modultyp":"rainyman","vars":

right before disabling the sql-logging seems to contain TWO datasets beginning with 

> modultyp":"rainyman"

I reformatted the JSON here:
[JSON received at 03-17-27.002.txt](https://github.com/t4qjXH8N/ioBroker.wiffi-wz/files/3184185/JSON.received.at.03-17-27.002.txt)

The second JSON part beginning in line 141 does not contain all states.
Do you by any chance then delete the states that are not contained in the JSON?

Greetings,
Markus

**Comment by Cumulus7** [comment]
Yesterday evening the history settings got lost again.
(both the normal history settings and sql logging)

`Time: 2019-05-16 23:40:22.100 `

There was a JSON received again with some of the rain-values missing. **So the adapter apparently deleted the states and later created them again!**

[Log_Part_2019-05-16 23-40.txt](https://github.com/t4qjXH8N/ioBroker.wiffi-wz/files/3190597/Log_Part_2019-05-16.23-40.txt)

**Comment by t4qjXH8N** [comment]
Yes, I am pretty sure that this is the problem. But how to deal with that?
At first, I like the idea that only those states are created that are
actually needed. But I think I am going to change the behaviour that way
that states are created only.

**Comment by Cumulus7** [comment]
Hi,

yes, creating **and** deleting states sounds nice, but problems like above can arise.
I think manually deleting old unused states is safer.

A change of this behaviour is greatly appreciated :-)

Greetings,
Markus

**Comment by t4qjXH8N** [comment]
There is a branch issue_13 that behaves so. Could you please check if it is working?

**Comment by Cumulus7** [comment]
Sorry for the question: how do i most easily update to this branch?

**Comment by Cumulus7** [comment]
Hi,
i still need help with the update to the new branch: how do i do that?

Greetings,
Markus

**Comment by t4qjXH8N** [comment]
In this simple case it is sufficient to download the main.js from the new
branch and replace the old main.js.

**Comment by Cumulus7** [comment]
THX. Just did that. I will report back in two weeks...

**Comment by Cumulus7** [comment]
Hi,
the new branch seems to have solved the problem successfully.

THX a lot!
Greetings,
Markus
