### ISSUE TITLE
Bewegungselder und Noise Status des Wiffi-wz werden nicht mehr übertagen.

### ISSUE THREAD

**Issue by smartboart** [t4qjXH8N/ioBroker.wiffi-wz#16]
hi, seit dem Update bekomme ich keine Statusänderung der beiden Bewegungsmelder und des Noise sensor des WiffiWZ an den Iobroker übertragen . Besteht das Problem noch bei wem anders oder muss hier bei mir weiter suchen...Auf der Gui des WiffiWZ wird die Bewegung und noise  erkannt... 
Werte werden aktualisiert aber stehen immer nur auf false... Um das zu verifizieren wollte ich auf die vorherige Version zurück, aber das funktioniert nicht...Wie kann ich downgraden...Einebestimmte Version über den Admin  hat nicht funktioniert

**Comment by smartboart** [comment]
die json des wiffiwz sieht hier vernünftig aus...siehe Auszug mit einem Bewegungsmelder true...im iobroker bleibt der false...
![Unbenannt](https://user-images.githubusercontent.com/38385805/59979507-1c866880-95e9-11e9-8f7f-9305066f628b.PNG)

**Comment by smartboart** [comment]
bin zurück auf 2.0.1 da besteht das Problem nicht... ist wahrscheinlich beim letzten Update wegen der States des Weatherman unter die Räder gekommen...

**Comment by t4qjXH8N** [comment]
Hey, kannst Du bitte die die Version 2.1.3 im Master-Branch testen?

**Comment by smartboart** [comment]
Hi, gerne...leider habe ich es nicht installiert bekommen. Bekomme folgende Meldung im log..
`

host.ioBroker-Rock | 2019-06-28 12:05:50.757 | info | Update repository "latest" under "http://download.iobroker.net/sources-dist-latest.json"
-- | -- | -- | --
iobroker | 2019-06-28 12:05:50.047 | info | exit 0
iobroker | 2019-06-28 12:05:49.942 | info | upload [0] wiffi-wz.admin /opt/iobroker/node_modules/iobroker.wiffi-wz/admin/index_m.html index_m.html text/html
iobroker | 2019-06-28 12:05:49.865 | info | upload [1] wiffi-wz.admin /opt/iobroker/node_modules/iobroker.wiffi-wz/admin/wiffi-wz.png wiffi-wz.png image/png
iobroker | 2019-06-28 12:05:49.774 | info | upload [2] wiffi-wz.admin /opt/iobroker/node_modules/iobroker.wiffi-wz/admin/words.js words.js application/javascript
iobroker | 2019-06-28 12:05:49.747 | info | got /opt/iobroker/node_modules/iobroker.wiffi-wz/admin
iobroker | 2019-06-28 12:05:49.614 | info | npm ERR!     /home/iobroker/.npm/_logs/2019-06-28T10_05_49_593Z-debug.log
iobroker | 2019-06-28 12:05:49.614 | info | npm ERR! A complete log of this run can be found in:
iobroker | 2019-06-28 12:05:49.594 | info | npm ERR! code ENOLOCALnpm ERR! Could not install from  "cd/opt/iobroker/etc/ioBroker.wiffi-wz" as it does not contain a  package.json file.
iobroker | 2019-06-28 12:05:28.828 | info | npm install cd/opt/iobroker/etc/ioBroker.wiffi-wz --production --save --prefix "/opt/iobroker" (System call)
iobroker | 2019-06-28 12:05:27.291 | info | install cd/opt/iobroker/etc/ioBroker.wiffi-wz
iobroker | 2019-06-28 12:05:26.217 | info | url "cd/opt/iobroker/etc/ioBroker.wiffi-wz" --debug
host.ioBroker-Rock | 2019-06-28 12:04:13.228 | info | Update repository "latest" under "http://download.iobroker.net/sources-dist-latest.json"
host.ioBroker-Rock | 2019-06-28 12:02:03.956 | info | Update repository "latest" under "http://download.iobroker.net/sources-dist-latest.json"
host.ioBroker-Rock | 2019-06-28 12:00:02.333 | info | instance system.adapter.feiertage.0 terminated with code 0 (OK)
javascript.0 | 2019-06-28 12:00:00.957 | info | script.js.common.Batterie_Netzüberwachung.BatterieanzeigeSmartboardWZ: Regelmäßige Ladung wird überwacht Prüfung läuft
host.ioBroker-Rock | 2019-06-28 12:00:00.055 | info | instance system.adapter.feiertage.0 started with pid 6738
host.ioBroker-Rock | 2019-06-28 11:55:07.572 | info | Update repository "latest" under "http://download.iobroker.net/sources-dist-latest.json"
iobroker | 2019-06-28 11:55:06.976 | info | exit 0
iobroker | 2019-06-28 11:55:06.887 | info | npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2019-06-28T09_55_06_875Z-debug.log
iobroker | 2019-06-28 11:55:06.886 | info |  
iobroker | 2019-06-28 11:55:06.870 | info | ERR! Could not install from "cd/opt/iobroker/etc/ioBroker.wiffi-wz-master" as it does not contain a package.json file.
iobroker | 2019-06-28 11:55:06.868 | info | npm
iobroker | 2019-06-28 11:55:06.864 | info | ENOLOCAL
iobroker | 2019-06-28 11:55:06.863 | info | ERR! code
iobroker | 2019-06-28 11:55:06.861 | info | npm
iobroker | 2019-06-28 11:54:46.430 | info | npm install cd/opt/iobroker/etc/ioBroker.wiffi-wz-master --production --save --prefix "/opt/iobroker" (System call)
iobroker | 2019-06-28 11:54:44.889 | info | install cd/opt/iobroker/etc/ioBroker.wiffi-wz-master
iobroker | 2019-06-28 11:54:43.865 | info | url "cd/opt/iobroker/etc/ioBroker.wiffi-wz-master" --debug
javascript.0 | 2019-06-28 11:44:01.080 | info | script.js.common.Batterie_Netzüberwachung.BatterienzeigeSmartboardBad:  Regelmäßige Ladung Tablet Bad wird überwacht, Prüfung läuft
host.ioBroker-Rock | 2019-06-28 11:40:09.252 | info | Update repository "latest" under "http://download.iobroker.net/sources-dist-latest.json"
iobroker | 2019-06-28 11:40:08.634 | info | exit 0
iobroker | 2019-06-28 11:40:08.543 | info | npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2019-06-28T09_40_08_530Z-debug.log
iobroker | 2019-06-28 11:40:08.541 | info |  
iobroker | 2019-06-28 11:40:08.526 | info | Could not install from "cd/opt/iobroker/etc/ioBroker.wiffi-wz-master" as it does not contain a package.json file.
iobroker | 2019-06-28 11:40:08.524 | info | ERR!
iobroker | 2019-06-28 11:40:08.523 | info | npm
iobroker | 2019-06-28 11:40:08.519 | info | ENOLOCAL
iobroker | 2019-06-28 11:40:08.517 | info | ERR! code
iobroker | 2019-06-28 11:40:08.516 | info | npm
iobroker | 2019-06-28 11:39:47.742 | info | npm install cd/opt/iobroker/etc/ioBroker.wiffi-wz-master --production --save --prefix "/opt/iobroker" (System call)
iobroker | 2019-06-28 11:39:46.224 | info | install cd/opt/iobroker/etc/ioBroker.wiffi-wz-master
iobroker | 2019-06-28 11:39:45.177 | info | url "cd/opt/iobroker/etc/ioBroker.wiffi-wz-master" --debug
host.ioBroker-Rock | 2019-06-28 11:37:47.522 | info | Update repository "latest" under "http://download.iobroker.net/sources-dist-latest.json"
iobroker | 2019-06-28 11:37:46.842 | info | exit 0

`

**Comment by smartboart** [comment]
so hier der log vom Test der Datenpunkte...
Der wiffi.wz ( im log die IP Endung 54 ) bringt wieder den Satus der Bewegungsmelder und des Noisesensor.
Der Weatherman (im log die IB Endung 52 ) scheint wieder diskrepanzen im Bereich der States zu haben ( string und boolean )

`

javascript.0 | 2019-06-28 12:41:01.460 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_52.w_windstaerke Solltyp: number Isttyp: string
-- | -- | -- | --
javascript.0 | 2019-06-28 12:41:01.459 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_52.w_windrichtung Solltyp: string Isttyp: string
javascript.0 | 2019-06-28 12:41:01.459 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_52.w_windchill Solltyp: number Isttyp: string
javascript.0 | 2019-06-28 12:41:01.458 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_52.w_wind_spitze Solltyp: number Isttyp: string
javascript.0 | 2019-06-28 12:41:01.458 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_52.w_wind_mittel Solltyp: number Isttyp: string
javascript.0 | 2019-06-28 12:41:01.457 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_52.w_wind_dir Solltyp: number Isttyp: string
javascript.0 | 2019-06-28 12:41:01.457 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_52.w_temperatur Solltyp: number Isttyp: string
javascript.0 | 2019-06-28 12:41:01.457 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_52.w_taupunkt Solltyp: number Isttyp: string
javascript.0 | 2019-06-28 12:41:01.456 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_52.w_sonnentemperatur Solltyp: number Isttyp: string
javascript.0 | 2019-06-28 12:41:01.456 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_52.w_sonnenstunden_heute Solltyp: number Isttyp: string
javascript.0 | 2019-06-28 12:41:01.455 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_52.w_sonne_diff_temp Solltyp: number Isttyp: string
javascript.0 | 2019-06-28 12:41:01.455 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_52.w_regenstunden_heute Solltyp: number Isttyp: string
javascript.0 | 2019-06-28 12:41:01.454 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_52.w_regenstaerke Solltyp: number Isttyp: string
javascript.0 | 2019-06-28 12:41:01.454 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_52.w_regensensor_wert Solltyp: number Isttyp: string
javascript.0 | 2019-06-28 12:41:01.454 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_52.w_regenmelder Solltyp: boolean Isttyp: string
javascript.0 | 2019-06-28 12:41:01.453 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_52.w_regen_mm_heute Solltyp: number Isttyp: string
javascript.0 | 2019-06-28 12:41:01.453 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_52.w_regen_mm_gestern Solltyp: number Isttyp: string
javascript.0 | 2019-06-28 12:41:01.452 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_52.w_regen_letzte_h Solltyp: number Isttyp: string
javascript.0 | 2019-06-28 12:41:01.452 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_52.w_minuten_vor_su Solltyp: number Isttyp: string
javascript.0 | 2019-06-28 12:41:01.452 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_52.w_minuten_vor_sa Solltyp: number Isttyp: string
javascript.0 | 2019-06-28 12:41:01.451 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_52.w_ip Solltyp: string Isttyp: string
javascript.0 | 2019-06-28 12:41:01.451 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_52.w_himmeltemperatur Solltyp: number Isttyp: string
javascript.0 | 2019-06-28 12:41:01.450 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_52.w_feuchte_abs Solltyp: number Isttyp: string
javascript.0 | 2019-06-28 12:41:01.450 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_52.w_elevation Solltyp: number Isttyp: string
javascript.0 | 2019-06-28 12:41:01.449 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_52.w_barotrend Solltyp: string Isttyp: string
javascript.0 | 2019-06-28 12:41:01.449 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_52.w_barometer Solltyp: number Isttyp: string
javascript.0 | 2019-06-28 12:41:01.444 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_52.w_azimut Solltyp: number Isttyp: string
javascript.0 | 2019-06-28 12:41:01.444 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_52.w_feuchte_rel Solltyp: number Isttyp: string
javascript.0 | 2019-06-28 12:41:01.443 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_52.w_temperatur Solltyp: number Isttyp: string
javascript.0 | 2019-06-28 12:41:01.443 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_52.w_sonne_scheint Solltyp: boolean Isttyp: string
javascript.0 | 2019-06-28 12:41:01.442 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_52.w_lux Solltyp: number Isttyp: string
javascript.0 | 2019-06-28 12:41:01.442 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_54.wz_azimut Solltyp: number Isttyp: number
javascript.0 | 2019-06-28 12:41:01.441 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_54.wz_baro Solltyp: number Isttyp: number
javascript.0 | 2019-06-28 12:41:01.440 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_54.wz_buzzer Solltyp: boolean Isttyp: boolean
javascript.0 | 2019-06-28 12:41:01.440 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_54.wz_co2 Solltyp: number Isttyp: number
javascript.0 | 2019-06-28 12:41:01.439 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_54.wz_elevation Solltyp: number Isttyp: number
javascript.0 | 2019-06-28 12:41:01.439 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_54.wz_feuchte_abs Solltyp: number Isttyp: number
javascript.0 | 2019-06-28 12:41:01.438 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_54.wz_ip Solltyp: string Isttyp: string
javascript.0 | 2019-06-28 12:41:01.438 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_54.wz_luftdrucktrend Solltyp: string Isttyp: string
javascript.0 | 2019-06-28 12:41:01.438 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_54.wz_lux Solltyp: number Isttyp: number
javascript.0 | 2019-06-28 12:41:01.437 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_54.wz_motion Solltyp: boolean Isttyp: boolean
javascript.0 | 2019-06-28 12:41:01.437 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_54.wz_temp Solltyp: number Isttyp: number
javascript.0 | 2019-06-28 12:41:01.436 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_54.wz_taupunkt Solltyp: number Isttyp: number
javascript.0 | 2019-06-28 12:41:01.436 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_54.wz_relais Solltyp: boolean Isttyp: boolean
javascript.0 | 2019-06-28 12:41:01.435 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_54.wz_noise Solltyp: boolean Isttyp: boolean
javascript.0 | 2019-06-28 12:41:01.435 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_54.wz_motion_left Solltyp: boolean Isttyp: boolean
javascript.0 | 2019-06-28 12:41:01.434 | info | script.js.common.Test.Test: ID: wiffi-wz.0.root.192_168_1_54.wz_motion_right Solltyp: boolean Isttyp: boolean
javascript.0 | 2019-06-28 12:41:01.425 | info | Start javascript script.js.common.Test.Test

`

**Comment by t4qjXH8N** [comment]
Hast Du gaaanz sicher den Stand aus dem Master-Branch? Es müsste reichen die main.js auszutauschen. Meine Tests sind alle positiv.

**Comment by t4qjXH8N** [comment]
Bin gerade nochmal alles durchgegangen, es tut bei mir. Sonst schick mir bitte das Telegramm vom Wiffi und vom Regenmelder, gerne auch per Mail an chvorholt@gmail.com .

**Comment by smartboart** [comment]
Mhhh dann muss ich nochmal schauen....habe ganz normal über den admin per URL upgedatet auf die master Version... Diese wird auch im admin 
![Screenshot_20190629_004208_org mozilla firefox](https://user-images.githubusercontent.com/38385805/60374969-54394a00-9a07-11e9-9bbc-e356b88af834.jpg)
angezeigt...

**Comment by smartboart** [comment]
ok, war mein Fehler. ich hätte die States alle löschen sollen nachdem update. Nachdem ich sie gelöscht habe und sie neu angelegt wurden. passt nun alles!!!
Topp!!! Danke für die Abhilfe...Wundert mich nur dass es sonst keinem aufgefallen ist...
