### ISSUE TITLE
Einige Datenpunkte kann ich nicht per Blockly weiterverarbeiten

### ISSUE THREAD

**Issue by guergen1** [t4qjXH8N/ioBroker.wiffi-wz#20]
Blockly weigert sich den folgenden Datenpunkt weiter zu verarbeiten:
`{
  "type": "state",
  "common": {
    "name": 1,
    "desc": "aussentemperatur",
    "unit": "°C",
    "role": "value",
    "id": "w_temperatur",
    "type": "number",
    "read": true,
    "write": false,
    "custom": {
      "influxdb.0": {
        "enabled": true,
        "changesOnly": true,
        "debounce": "",
        "retention": "31536000",
        "changesRelogInterval": "1800",
        "changesMinDelta": 0,
        "storageType": "Number",
        "aliasId": "Aussentemperatur"
      }
    }
  },
  "native": {},
  "from": "system.adapter.wiffi-wz.0",
  "user": "system.user.admin",
  "ts": 1566662224431,
  "_id": "wiffi-wz.0.root.192_168_1_142.w_temperatur",
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  }
}
`

Bei diesem Wert geht es:
`{
  "type": "state",
  "common": {
    "read": true,
    "write": false,
    "desc": "regen_mm_gestern",
    "unit": "mm",
    "role": "value",
    "id": "w_regen_mm_gestern",
    "name": "27",
    "type": "number"
  },
  "native": {},
  "from": "system.adapter.wiffi-wz.0",
  "user": "system.user.admin",
  "ts": 1566662224436,
  "_id": "wiffi-wz.0.root.192_168_1_142.w_regen_mm_gestern",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

Warum ist das so?
Wenn ich den ersten Wert per js-in einen eigenen DP "umsetze", kann ich ihn verarbeiten!

**Comment by t4qjXH8N** [comment]
Hallo Guergen1, 
das weiß ich nicht. Was sagen denn die Entwickler von Blockly?

**Comment by guergen1** [comment]
Wer sind denn die Entwickler von Blockly? Die Javascript-Leute?

**Comment by t4qjXH8N** [comment]
Ich vermute ja. Eine genauere Antwort kann ich Dir leider nicht geben. Du kannst Dich gerne bei mir melden, wenn die Blockly-Entwickler die Ursache für den Fehler gefunden haben.

**Comment by guergen1** [comment]
> Ich vermute ja. Eine genauere Antwort kann ich Dir leider nicht geben. Du kannst Dich gerne bei mir melden, wenn die Blockly-Entwickler die Ursache für den Fehler gefunden haben.

DiE Dp sind falsch deklariert, im oberen steht name, es ist aber ein string (1).
Kann es zu Problemen kommen, wenn ich das selbst im broker ändere?
Oder wäre es besser es im Adapter anzupassen?
Zumindest für folgende Nutzer!

**Comment by guergen1** [comment]
Antwort von Apollon77: 
Das "27" ist in dem unteren wo es ja auch tut :-) Aber oben ist es eine Zahl.

Also hier ggf Issue beim wiffi adapter anlegen das "common.name" bitte immer als String gesetzt wird

**Comment by guergen1** [comment]
No 20 müsstest Du wieder öffnen...!

Ralf

Von Unterwegs gesendet

**Comment by t4qjXH8N** [comment]
Alles klar, ich werde mich im Laufe der Woche drum kümmern.

**Comment by guergen1** [comment]
Es sind mehrere Datenpunkt, wo das nicht stimmt... Temperatur, Wind und Windstärke, sind die, wo ich es bemert habe!
Vielleicht guckst Du dir alle an :-)

**Comment by guergen1** [comment]
Hallo, bist Du schon weiter gekommen?

**Comment by t4qjXH8N** [comment]
Hey, ich habe das Problem einfach beheben können. Kannst Du bitte den Branch "issue_#20" ausschecken und testen?

**Comment by guergen1** [comment]
Das lässt sich nicht installieren:
$ ./iobroker url "https://github.com/t4qjXH8N/ioBroker.wiffi-wz/tree/issue_%2320" --debug
install https://github.com/t4qjXH8N/ioBroker.wiffi-wz/tree/issue_%2320/tarball/f3b787f21f8ce1fcd54e23ffe0cdbfe47d9a77bb
NPM version: 6.13.7
npm install https://github.com/t4qjXH8N/ioBroker.wiffi-wz/tree/issue_%2320/tarball/f3b787f21f8ce1fcd54e23ffe0cdbfe47d9a77bb --loglevel error --prefix "/opt/iobroker" (System call)
npm
 ERR!
 code E404
npm
 ERR! 
404 Not Found - GET https://github.com/t4qjXH8N/ioBroker.wiffi-wz/tree/issue_%2320/tarball/f3b787f21f8ce1fcd54e23ffe0cdbfe47d9a77bbnpm
 ERR! 404 
npm ERR!
 404  'https://github.com/t4qjXH8N/ioBroker.wiffi-wz/tree/issue_%2320/tarball/f3b787f21f8ce1fcd54e23ffe0cdbfe47d9a77bb' is not in the npm registry.
npm ERR!
 404 Your package name is not valid, because npm ERR! 404  1. name can only contain URL-friendly charactersnpm ERR! 404  2. name can no longer contain capital lettersnpm ERR!
 404 npm ERR! 404 Note that you can also install from anpm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2020-02-08T08_58_42_810Z-debug.log
upload [2] wiffi-wz.admin /opt/iobroker/node_modules/iobroker.wiffi-wz/admin/words.js words.js application/javascript
upload [1] wiffi-wz.admin /opt/iobroker/node_modules/iobroker.wiffi-wz/admin/wiffi-wz.png wiffi-wz.png image/png
upload [0] wiffi-wz.admin /opt/iobroker/node_modules/iobroker.wiffi-wz/admin/index_m.html index_m.html text/html
process exited with code 0

**Comment by guergen1** [comment]
Ändere grade von Hand die entsprechende Datei main.js

**Comment by t4qjXH8N** [comment]
Versuch es sonst jetzt mal ohne die Raute hinter issue

**Comment by guergen1** [comment]
Hat zu Fuss geklappt
Kann den Wert jetzt weiter verarbeiten. Blockly lässt das auswählen/speichern des Wertes jetzt zu!

**Comment by guergen1** [comment]
Danke!

**Comment by t4qjXH8N** [comment]
Alles klar!
