### ISSUE TITLE
Update stable version in repo to 2.2.0

### ISSUE THREAD

**Issue by GermanBluefox** [t4qjXH8N/ioBroker.wiffi-wz#24]
# Think about update stable version to 2.2.0
**Version**: stable=**2.1.4** (185 days old) => latest=**2.2.0** (25 days old)
**Installs**: stable=**109** (57.98%), latest=**67** (35.64%), total=**188**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L1531)

**Comment by t4qjXH8N** [comment]
Done.
