### ISSUE TITLE
Datenpunkte können nicht zuverlässig verarbeitet werden

### ISSUE THREAD

**Issue by guergen1** [t4qjXH8N/ioBroker.wiffi-wz#26]
Wenn ich die Datenpunkte der Wetterstation im Blockly weiterverarbeitete und das Script starte, sich ein paar Werte ändern, zerschiesst sich das Blockly soweit, dass ich den IoBroker aus einem Backup zurückspielen muss.
Ein Debuglog habe ich nicht, da es sich zwar reproduzieren lassen kann, aber dort nichts drin steht. Das Script bricht ab und der Blocklycode ist nicht mehr da!
es geht mir vor allem um die Werte "Regensensor-Wert" (18) und "Windspitze"(5).
Habe zwar schon versucht, die Werte in Zahlen zu konvertieren um damit arbeiten zu können, leider ohne Erfolg

**Comment by guergen1** [comment]
Das bleibt aus einem relativ grossen Blockly übrig:
![grafik](https://user-images.githubusercontent.com/34395245/79050861-271ff600-7c2d-11ea-9427-7b7860752e6e.png)
 Und das ist der Fehler:
![grafik](https://user-images.githubusercontent.com/34395245/79050884-44ed5b00-7c2d-11ea-80b1-8529ddfa01af.png)

**Comment by t4qjXH8N** [comment]
Ich benötige das Datagramm aus dem Debuglog und das in JavaScript umgewandelte Blockly.

**Comment by guergen1** [comment]
OK, muss erst ein Backup einspielen... kann das definitiv mit den beiden Werten reproduzieren!

**Comment by guergen1** [comment]
Hier aber mal der auszug aus dem Log, der grade passiert ist: (Datenpunkte existieren)
`

javascript.0 | 2020-04-12 08:37:38.909 | warn | (18918)     at processImmediate (timers.js:658:5)
-- | -- | -- | --
javascript.0 | 2020-04-12 08:37:38.909 | warn | (18918)     at tryOnImmediate (timers.js:676:5)
javascript.0 | 2020-04-12 08:37:38.909 | warn | (18918)     at runCallback (timers.js:705:18)
javascript.0 | 2020-04-12 08:37:38.909 | warn | (18918)     at Immediate.setImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4851:37)
javascript.0 | 2020-04-12 08:37:38.909 | warn | (18918)     at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:450:25)
javascript.0 | 2020-04-12 08:37:38.909 | warn | (18918)     at Object.callback (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1123:38)
javascript.0 | 2020-04-12 08:37:38.909 | warn | (18918)     at Object.<anonymous> (script.js.common.Wiffi-wz_wandeln.Wind-Regen:5:70)
javascript.0 | 2020-04-12 08:37:38.908 | warn | (18918) getState "0_userdata.0.wiffi-wz.Wind-Spitze" not found (3)
influxdb.0 | 2020-04-12 08:37:36.535 | info | (18971) enabled logging of Wind spitze, Alias=true
javascript.0 | 2020-04-12 08:37:23.061 | warn | (18918)     at processImmediate (timers.js:658:5)
javascript.0 | 2020-04-12 08:37:23.061 | warn | (18918)     at tryOnImmediate (timers.js:676:5)
javascript.0 | 2020-04-12 08:37:23.060 | warn | (18918)     at runCallback (timers.js:705:18)
javascript.0 | 2020-04-12 08:37:23.060 | warn | (18918)     at Immediate.setImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4851:37)
javascript.0 | 2020-04-12 08:37:23.060 | warn | (18918)     at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:450:25)
javascript.0 | 2020-04-12 08:37:23.060 | warn | (18918)     at Object.callback (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1123:38)
javascript.0 | 2020-04-12 08:37:23.060 | warn | (18918)     at Object.<anonymous> (script.js.common.Wiffi-wz_wandeln.Wind-Regen:13:75)
javascript.0 | 2020-04-12 08:37:23.057 | warn | (18918) getState "0_userdata.0.wiffi-wz.Regensensor" not found (3)

`

**Comment by guergen1** [comment]
Wenn der Wert Wind in den neuen DP geschrieben werden soll, stürzt das komplette System ab. der Datenpunkt Wind ist dann nicht mehr nutzbar, erst wieder nach einem restore des Brokers

**Comment by guergen1** [comment]
Hier ist das Script:
`on({id: "wiffi-wz.0.root.192_168_1_142.w_wind_spitze"/*5*/, change: "ne"}, function (obj) {
  var value = obj.state.val;
  var oldValue = obj.oldState.val;
  if (getState("wiffi-wz.0.root.192_168_1_142.w_wind_spitze").val != getState("0_userdata.0.wind").val) {
    setState("0_userdata.0.wind"/*wind*/, getState("wiffi-wz.0.root.192_168_1_142.w_wind_spitze").val, true);
  }
});

//JTNDeG1sJTIweG1sbnMlM0QlMjJodHRwJTNBJTJGJTJGd3d3LnczLm9yZyUyRjE5OTklMkZ4aHRtbCUyMiUzRSUzQ2Jsb2NrJTIwdHlwZSUzRCUyMm9uJTIyJTIwaWQlM0QlMjIlN0JMJTNBIWIlMjVEOCpNb2djemM5JTIzMGVpJTIyJTIweCUzRCUyMjg4JTIyJTIweSUzRCUyMi00ODclMjIlM0UlM0NmaWVsZCUyMG5hbWUlM0QlMjJPSUQlMjIlM0V3aWZmaS13ei4wLnJvb3QuMTkyXzE2OF8xXzE0Mi53X3dpbmRfc3BpdHplJTNDJTJGZmllbGQlM0UlM0NmaWVsZCUyMG5hbWUlM0QlMjJDT05ESVRJT04lMjIlM0VuZSUzQyUyRmZpZWxkJTNFJTNDZmllbGQlMjBuYW1lJTNEJTIyQUNLX0NPTkRJVElPTiUyMiUzRSUzQyUyRmZpZWxkJTNFJTNDc3RhdGVtZW50JTIwbmFtZSUzRCUyMlNUQVRFTUVOVCUyMiUzRSUzQ2Jsb2NrJTIwdHlwZSUzRCUyMmNvbnRyb2xzX2lmJTIyJTIwaWQlM0QlMjI2VFolMjNOJTI0eFElNUIoandzc1hGTSUyQ21qJTIyJTNFJTNDdmFsdWUlMjBuYW1lJTNEJTIySUYwJTIyJTNFJTNDYmxvY2slMjB0eXBlJTNEJTIybG9naWNfY29tcGFyZSUyMiUyMGlkJTNEJTIybGFKS2lZYW1pRSU3Qk8xJTI1SmMlM0ElNUR+JTNGJTIyJTNFJTNDZmllbGQlMjBuYW1lJTNEJTIyT1AlMjIlM0VORVElM0MlMkZmaWVsZCUzRSUzQ3ZhbHVlJTIwbmFtZSUzRCUyMkElMjIlM0UlM0NibG9jayUyMHR5cGUlM0QlMjJnZXRfdmFsdWUlMjIlMjBpZCUzRCUyMm4uTyU3REclM0JsJTNBX1hLNyUyQ3BZZlUlNDBWJTNCJTIyJTNFJTNDZmllbGQlMjBuYW1lJTNEJTIyQVRUUiUyMiUzRXZhbCUzQyUyRmZpZWxkJTNFJTNDZmllbGQlMjBuYW1lJTNEJTIyT0lEJTIyJTNFd2lmZmktd3ouMC5yb290LjE5Ml8xNjhfMV8xNDIud193aW5kX3NwaXR6ZSUzQyUyRmZpZWxkJTNFJTNDJTJGYmxvY2slM0UlM0MlMkZ2YWx1ZSUzRSUzQ3ZhbHVlJTIwbmFtZSUzRCUyMkIlMjIlM0UlM0NibG9jayUyMHR5cGUlM0QlMjJnZXRfdmFsdWUlMjIlMjBpZCUzRCUyMlNZWCU3QnMlMjMlM0RtMyUyMyU3RENtfiU2MCU1RCFyRSUzRiUyMiUzRSUzQ2ZpZWxkJTIwbmFtZSUzRCUyMkFUVFIlMjIlM0V2YWwlM0MlMkZmaWVsZCUzRSUzQ2ZpZWxkJTIwbmFtZSUzRCUyMk9JRCUyMiUzRTBfdXNlcmRhdGEuMC53aW5kJTNDJTJGZmllbGQlM0UlM0MlMkZibG9jayUzRSUzQyUyRnZhbHVlJTNFJTNDJTJGYmxvY2slM0UlM0MlMkZ2YWx1ZSUzRSUzQ3N0YXRlbWVudCUyMG5hbWUlM0QlMjJETzAlMjIlM0UlM0NibG9jayUyMHR5cGUlM0QlMjJ1cGRhdGUlMjIlMjBpZCUzRCUyMlVMJTVEU3BqYjY0eWp1OXlDQXk5eCU0MCUyMiUzRSUzQ211dGF0aW9uJTIwZGVsYXlfaW5wdXQlM0QlMjJmYWxzZSUyMiUzRSUzQyUyRm11dGF0aW9uJTNFJTNDZmllbGQlMjBuYW1lJTNEJTIyT0lEJTIyJTNFMF91c2VyZGF0YS4wLndpbmQlM0MlMkZmaWVsZCUzRSUzQ2ZpZWxkJTIwbmFtZSUzRCUyMldJVEhfREVMQVklMjIlM0VGQUxTRSUzQyUyRmZpZWxkJTNFJTNDdmFsdWUlMjBuYW1lJTNEJTIyVkFMVUUlMjIlM0UlM0NibG9jayUyMHR5cGUlM0QlMjJnZXRfdmFsdWUlMjIlMjBpZCUzRCUyMnZxWColM0RxbUJGLUwqVzcyQlZ2TGwlMjIlM0UlM0NmaWVsZCUyMG5hbWUlM0QlMjJBVFRSJTIyJTNFdmFsJTNDJTJGZmllbGQlM0UlM0NmaWVsZCUyMG5hbWUlM0QlMjJPSUQlMjIlM0V3aWZmaS13ei4wLnJvb3QuMTkyXzE2OF8xXzE0Mi53X3dpbmRfc3BpdHplJTNDJTJGZmllbGQlM0UlM0MlMkZibG9jayUzRSUzQyUyRnZhbHVlJTNFJTNDJTJGYmxvY2slM0UlM0MlMkZzdGF0ZW1lbnQlM0UlM0MlMkZibG9jayUzRSUzQyUyRnN0YXRlbWVudCUzRSUzQyUyRmJsb2NrJTNFJTNDJTJGeG1sJTNF`

**Comment by guergen1** [comment]
Und hier der zweite Teil:
`on({id: "wiffi-wz.0.root.192_168_1_142.w_regensensor_wert"/*18*/, change: "ne"}, function (obj) {
  var value = obj.state.val;
  var oldValue = obj.oldState.val;
  if (getState("wiffi-wz.0.root.192_168_1_142.w_regensensor_wert").val != getState("0_userdata.0.regen").val) {
    setState("0_userdata.0.regen"/*regen*/, getState("wiffi-wz.0.root.192_168_1_142.w_regensensor_wert").val, true);
  }
});`

**Comment by guergen1** [comment]
Hat etwas gedauert, da ich di eVM auch wiederherstellen musste...
Hier das Log:
`

admin.0 | 2020-04-12 10:13:23.845 | debug | (12212) Subscribes: dummy
-- | -- | -- | --
admin.0 | 2020-04-12 10:13:23.844 | debug | (12212) Subscribe LOGS
admin.0 | 2020-04-12 10:13:23.714 | debug | (12212) Disable logging, because no one socket connected
admin.0 | 2020-04-12 10:13:23.714 | debug | (12212) Unsubscribe LOGS: dummy
admin.0 | 2020-04-12 10:13:23.713 | debug | (12212) Unsubscribe OBJECTS: system.adapter.javascript.*
admin.0 | 2020-04-12 10:13:23.713 | debug | (12212) Unsubscribe OBJECTS: script.*
admin.0 | 2020-04-12 10:13:23.713 | debug | (12212) Unsubscribe STATES: javascript.0.scriptProblem.*
admin.0 | 2020-04-12 10:13:23.712 | debug | (12212) Unsubscribe STATES: system.adapter.javascript.*.alive
admin.0 | 2020-04-12 10:13:22.846 | debug | (12212) Subscribes: system.adapter.javascript.*.alive, javascript.0.scriptProblem.*
admin.0 | 2020-04-12 10:13:22.846 | debug | (12212) Subscribe STATES: javascript.0.scriptProblem.*
admin.0 | 2020-04-12 10:13:17.545 | debug | (12212) Subscribes: system.adapter.javascript.*.alive
admin.0 | 2020-04-12 10:13:17.545 | debug | (12212) Subscribe STATES: system.adapter.javascript.*.alive
admin.0 | 2020-04-12 10:13:17.545 | debug | (12212) Subscribes: dummy
admin.0 | 2020-04-12 10:13:17.544 | debug | (12212) Subscribe LOGS
admin.0 | 2020-04-12 10:13:17.544 | debug | (12212) Subscribe OBJECTS: system.adapter.javascript.*
admin.0 | 2020-04-12 10:13:17.543 | debug | (12212) Subscribe OBJECTS: script.*
admin.0 | 2020-04-12 10:13:17.288 | debug | (12212) Subscribes:
admin.0 | 2020-04-12 10:13:17.288 | debug | (12212) Unsubscribe STATES: wiffi-wz.0.root.192_168_1_142.*
admin.0 | 2020-04-12 10:13:17.287 | debug | (12212) Subscribes: wiffi-wz.0.root.192_168_1_142.*
admin.0 | 2020-04-12 10:13:17.286 | debug | (12212) Unsubscribe STATES: 0_userdata.0.*
javascript.0 | 2020-04-12 10:13:12.689 | warn | (1157)     at processImmediate (timers.js:658:5)
javascript.0 | 2020-04-12 10:13:12.689 | warn | (1157)     at tryOnImmediate (timers.js:676:5)
javascript.0 | 2020-04-12 10:13:12.689 | warn | (1157)     at runCallback (timers.js:705:18)
javascript.0 | 2020-04-12 10:13:12.689 | warn | (1157)     at Immediate.setImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4851:37)
javascript.0 | 2020-04-12 10:13:12.689 | warn | (1157)     at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:450:25)
javascript.0 | 2020-04-12 10:13:12.689 | warn | (1157)     at Object.callback (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1123:38)
javascript.0 | 2020-04-12 10:13:12.689 | warn | (1157)     at Object.<anonymous> (script.js.common.wiffi_wandeln.Wind_Regen:11:75)
javascript.0 | 2020-04-12 10:13:12.686 | warn | (1157) getState "0_userdata.0.Wiffi-wz.Regenwert" not found (3)
influxdb.0 | 2020-04-12 10:13:08.370 | info | (759) enabled logging of Wind spitze, Alias=true
influxdb.0 | 2020-04-12 10:12:58.748 | info | (759) enabled logging of Regensensorwert, Alias=true
admin.0 | 2020-04-12 10:12:50.157 | debug | (12212) Subscribes: 0_userdata.0.*, wiffi-wz.0.root.192_168_1_142.*
admin.0 | 2020-04-12 10:12:50.156 | debug | (12212) Subscribe STATES: wiffi-wz.0.root.192_168_1_142.*
admin.0 | 2020-04-12 10:12:40.683 | debug | (12212) Subscribes: 0_userdata.0.*
admin.0 | 2020-04-12 10:12:40.683 | debug | (12212) Subscribe STATES: 0_userdata.0.*
admin.0 | 2020-04-12 10:12:40.617 | debug | (12212) Disable logging, because no one socket connected
admin.0 | 2020-04-12 10:12:40.617 | debug | (12212) Unsubscribe LOGS: dummy
admin.0 | 2020-04-12 10:12:40.617 | debug | (12212) Unsubscribe OBJECTS: system.adapter.javascript.*
admin.0 | 2020-04-12 10:12:40.616 | debug | (12212) Unsubscribe OBJECTS: script.*
admin.0 | 2020-04-12 10:12:40.616 | debug | (12212) Unsubscribe STATES: javascript.0.scriptProblem.*
admin.0 | 2020-04-12 10:12:40.616 | debug | (12212) Unsubscribe STATES: system.adapter.javascript.*.alive
admin.0 | 2020-04-12 10:12:30.528 | debug | (12212) Subscribes: system.adapter.javascript.*.alive, javascript.0.scriptProblem.*
admin.0 | 2020-04-12 10:12:30.527 | debug | (12212) Subscribe STATES: javascript.0.scriptProblem.*
admin.0 | 2020-04-12 10:12:29.103 | debug | (12212) system.adapter.admin.0: logging true
javascript.0 | 2020-04-12 10:12:29.099 | debug | (1157) system.adapter.admin.0: logging true
admin.0 | 2020-04-12 10:12:29.096 | debug | (12212) Subscribes: system.adapter.javascript.*.alive
admin.0 | 2020-04-12 10:12:29.095 | debug | (12212) Subscribe STATES: system.adapter.javascript.*.alive
admin.0 | 2020-04-12 10:12:29.093 | debug | (12212) Subscribes: dummy
admin.0 | 2020-04-12 10:12:29.092 | debug | (12212) Change log subscriber state: true
admin.0 | 2020-04-12 10:12:29.092 | debug | (12212) Subscribe LOGS
admin.0 | 2020-04-12 10:12:29.076 | debug | (12212) Subscribe OBJECTS: system.adapter.javascript.*
admin.0 | 2020-04-12 10:12:29.075 | debug | (12212) Subscribe OBJECTS: script.*
host.iobroker | 2020-04-12 10:12:28.965 | info | instance system.adapter.wiffi-wz.0 terminated with code 156 (156)
admin.0 | 2020-04-12 10:12:28.468 | debug | (12212) Subscribes:
admin.0 | 2020-04-12 10:12:28.467 | debug | (12212) Unsubscribe STATES: system.host.*
wiffi-wz.0 | 2020-04-12 10:12:28.451 | info | (12549) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
admin.0 | 2020-04-12 10:12:28.447 | debug | (12212) Unsubscribe OBJECTS: system.host.*
wiffi-wz.0 | 2020-04-12 10:12:28.090 | info | (12549) Adapter stopped.
wiffi-wz.0 | 2020-04-12 10:12:28.090 | debug | (12549) Server closed
wiffi-wz.0 | 2020-04-12 10:12:28.089 | info | (12549) Stopping adapter ...
host.iobroker | 2020-04-12 10:12:28.088 | info | stopInstance system.adapter.wiffi-wz.0 killing pid 12549
admin.0 | 2020-04-12 10:12:27.922 | debug | (12212) Subscribes: system.host.*
admin.0 | 2020-04-12 10:12:27.921 | debug | (12212) Subscribe STATES: system.host.*
admin.0 | 2020-04-12 10:12:27.920 | debug | (12212) Subscribe OBJECTS: system.host.*
admin.0 | 2020-04-12 10:12:27.918 | debug | (12212) Subscribes: no subscribes
admin.0 | 2020-04-12 10:12:27.918 | debug | (12212) Subscribes: no subscribes
admin.0 | 2020-04-12 10:12:27.917 | debug | (12212) Subscribes: no subscribes
host.iobroker | 2020-04-12 10:12:27.572 | warn | instance system.adapter.wiffi-wz.0 still running with pid 12549
wiffi-wz.0 | 2020-04-12 10:12:25.688 | debug | (12549) Create basic states for Wiffi with ip 192.168.1.142
wiffi-wz.0 | 2020-04-12 10:12:25.687 | debug | (12549) Create basic states for Wiffi with ip 192.168.1.14

`

**Comment by guergen1** [comment]
Habe den Admin, javascript und wiffi.wz im debug laufen

**Comment by guergen1** [comment]
Erstelle ich mir DP Wind und Regenwert selbst und probiere das aus, geht mein Script

**Comment by t4qjXH8N** [comment]
Bitte schau mal zunächst ins Log. Du bekommst Warnungen, dass einige Datenpunkte nicht existieren. Was hat es damit auf sich? Läuft der Adapter im Compact-Mode?

**Comment by guergen1** [comment]
Die Datenpunkte sind definitiv da!
Aber ich glaube ich habe den Fehler jetzt selbst gefunden: Ich habe bei den wiffi-dp das schreiben erlaubt um regenwerte "zu fuss" zu ändern. Wenn ich das gemacht habe, fliegt mir das Script auseinander

**Comment by t4qjXH8N** [comment]
Kann es sein, daß du da eine wechselseitige Abhängigkeit geschaffen hast?
Also ändere A wenn sich B ändert und andersherum?

**Comment by guergen1** [comment]
Folgendes habe ich gebaut: 
`var maximaler_Wind_lang, maximaler_Wind_kurz, timeoutWind;


on({id: 'wiffi-wz.0.root.192_168_1_142.w_wind_spitze', change: "ne"}, function (obj) {
  var value = obj.state.val;
  var oldValue = obj.oldState.val;
  if (getState("wiffi-wz.0.root.192_168_1_142.w_wind_spitze").val >= maximaler_Wind_lang && getState("shelly.0.SHSW-25#112ED9#1.Shutter.Position").val > 25 || getState("wiffi-wz.0.root.192_168_1_142.w_wind_spitze").val >= maximaler_Wind_kurz && getState("shelly.0.SHSW-25#112ED9#1.Shutter.Position").val <= 25) {
    setState("0_userdata.0.Markise.Windsperrzeit"/*Windsperrzeit*/, true);
    console.warn('Windsperre 5 Min');
    (function () {if (timeoutWind) {clearTimeout(timeoutWind); timeoutWind = null;}})();
    timeoutWind = setTimeout(function () {
      setState("0_userdata.0.Markise.Windsperrzeit"/*Windsperrzeit*/, false);
      console.warn('Windsperre beendet');
    }, 300000);
  }
});`

**Comment by guergen1** [comment]
Das gehört noch dazu;
var maximaler_Wind_kurz, maximaler_Wind_lang;


maximaler_Wind_kurz = 7.2;
maximaler_Wind_lang = 5.9;

**Comment by t4qjXH8N** [comment]
Ich kann das aus der Ferne den Fehler leider nicht finden. Die wichtigste.
Frage für mich ist, ob es Fehler im Adapter ist. Im Moment sieht das für
mich nicht so aus. Sorry, kann da nicht helfen.

>

**Comment by guergen1** [comment]
Ok, werde es dann weiter beobachten. Ich denke es liegt daran, dass ich die wiffi-Werte von Hand ändere und irgendwas das nicht mag....

**Comment by guergen1** [comment]
Wünsche weiterhin frohe Ostern!
