### ISSUE TITLE
has no existing object JS-Controller 3.2.x

### ISSUE THREAD

**Issue by crunchip77** [t4qjXH8N/ioBroker.wiffi-wz#31]
folgende Meldung erscheint seit dem Upgrade des Js-Controllers
Verwende einen Pulscounter stall.biz
`31972) State "wiffi-wz.0.info.connection" has no existing object, this might lead to an error in future versions`

**Comment by smartboart** [comment]
wiffi-wz.0 | 2021-03-05 11:07:56.069 | warn | (2218) State "wiffi-wz.0.info.connection" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
