### ISSUE TITLE
js-controller 3.3.x

### ISSUE THREAD

**Issue by guergen1** [t4qjXH8N/ioBroker.wiffi-wz#34]
Nach dem Update auf den aktuellen js-controller folgender log-Eintrag:
`2021-05-01 00:00:32.055  - [33mwarn[39m: wiffi-wz.0 (25505) State value to set for "wiffi-wz.0.root.192_168_1_142.w_elevation" has value "-21.6" less than min "360"`

**Comment by foxriver76** [comment]
After sunset the elevation is negative, from my point of view the min needs to be corrected, actually the min is 0 and not 360 (which is max), but there was a bug in the logging.
