### ISSUE TITLE
Please add to stable repository if adapter is working for users

### ISSUE THREAD

**Issue by Apollon77** [t4qjXH8N/ioBroker.wiffi-wz#4]

**Comment by t4qjXH8N** [comment]
It seems that the current version is fairly stable. But how do I add the adapter correctly to the stable repository?

**Comment by GermanBluefox** [comment]
https://youtu.be/7N8fsJcAdlE?t=9m54s

https://github.com/ioBroker/ioBroker.repositories

**Comment by t4qjXH8N** [comment]
Thank you very much!

**Comment by t4qjXH8N** [comment]
@GermanBluefox and @Apollon77 thank you very much for your help, I think now I got it.
