### ISSUE TITLE
keine Daten vom weatherman-controller

### ISSUE THREAD

**Issue by Farmer-cb** [t4qjXH8N/ioBroker.wiffi-wz#5]
in weatherman sind daten vorhanden, 
![weatherman](https://user-images.githubusercontent.com/38419234/44895322-1e96d800-acf4-11e8-8a92-f649e7234de3.jpg)

aber leider kommen keine Daten in iobroker an.
![wiffi_dp](https://user-images.githubusercontent.com/38419234/44895314-163e9d00-acf4-11e8-9f14-21a75d58057d.png)

ich denke ich habe den controller richtig konfiguriert:
![expert](https://user-images.githubusercontent.com/38419234/44895332-2a829a00-acf4-11e8-8793-443c6d6bb210.jpg)

aktuelle Version 1.2.4 hab ich

im adapter die iobroker adresse als lokale server-ip ausgewählt
hab den adapter auch schon im debug-modus laufen, es kamen aber bisher keine relevanten Daten
`2018-08-31 07:33:00.588 - debug: wiffi-wz.0 redis pmessage io.*.logging io.system.adapter.admin.0.logging {"val":false,"ack":true,"ts":1535693580586,"q":0,"from":"system.adapter.admin.0","lc":1535693580586}
2018-08-31 07:33:00.590 - debug: wiffi-wz.0 system.adapter.admin.0: logging false
2018-08-31 07:46:16.845 - debug: wiffi-wz.0 redis pmessage io.*.logging io.system.adapter.admin.0.logging {"val":true,"ack":true,"ts":1535694376844,"q":0,"from":"system.adapter.admin.0","lc":1535694376844}
2018-08-31 07:46:16.846 - debug: wiffi-wz.0 system.adapter.admin.0: logging true`

json liefert:
`{"modultyp":"weatherman","vars":[{"name":"0","homematic_name":"w_ip","desc":"weatherman_ip","type":"string","unit":"","value":"192.168.xxx.yy"},{"name":"1","homematic_name":"w_temperature","desc":"aussentemperatur","type":"number","unit":"gradC","value":16.9},{"name":"21","homematic_name":"w_windchill","desc":"gefuehlte_temperatur","type":"number","unit":"gradC","value":16.9},{"name":"9","homematic_name":"w_taupunkt","desc":"taupunkt_temperatur","type":"number","unit":"gradC","value":9.1},{"name":"29","homematic_name":"w_temp_gestern","desc":"temp_m_gestern","type":"number","unit":"gradC","value":0.0},{"name":"14","homematic_name":"w_sky_temp","desc":"himmel_temperatur","type":"number","unit":"gradC","value":0.0},{"name":"2","homematic_name":"w_humidity","desc":"rel_feuchte","type":"number","unit":"%","value":60.0},{"name":"17","homematic_name":"w_hum_abs","desc":"abs_feuchte","type":"number","unit":"g/m3","value":8.6},{"name":"18","homematic_name":"w_rain_activity","desc":"regenmelderwert","type":"number","unit":"","value":6},{"name":"7","homematic_name":"w_rain_status","desc":"regenstatus","type":"boolean","unit":"","value":false},{"name":"8","homematic_name":"w_rain_intensity","desc":"regenstaerke","type":"number","unit":"mm/h","value":0.0},{"name":"19","homematic_name":"w_rain_volume_1","desc":"regen_pro_h","type":"number","unit":"mm","value":0.0},{"name":"20","homematic_name":"w_rain_volume_24","desc":"regen_pro_24h","type":"number","unit":"mm","value":0.0},{"name":"27","homematic_name":"w_rain_yesterday","desc":"regen_gestern","type":"number","unit":"mm","value":0.0},{"name":"3","homematic_name":"w_barometer","desc":"nn_luftdruck","type":"number","unit":"mb","value":1300.00},{"name":"11","homematic_name":"w_barotrend","desc":"luftdrucktrend","type":"string","unit":"","value":"not_valid"},{"name":"4","homematic_name":"w_wind_avg","desc":"avg_windgeschwindigkeit","type":"number","unit":"m/s","value":0.0},{"name":"5","homematic_name":"w_wind_peak","desc":"peak_windgeschwindigkeit","type":"number","unit":"m/s","value":0.0},{"name":"24","homematic_name":"w_windstaerke","desc":"bft_windgeschwindigkeit","type":"number","unit":"bft","value":0},{"name":"23","homematic_name":"w_wind_direction","desc":"windrichtung","type":"string","unit":"","value":"N"},{"name":"6","homematic_name":"w_wind_dir","desc":"windwinkel","type":"number","unit":"grad","value":0},{"name":"10","homematic_name":"w_lux","desc":"helligkeit","type":"number","unit":"lux","value":0.0},{"name":"15","homematic_name":"w_sun_temp","desc":"sonnentemperatur","type":"number","unit":"gradC","value":18.0},{"name":"22","homematic_name":"w_diff_temp","desc":"sonnen_difftemperatur","type":"number","unit":"gradC","value":1.1},{"name":"16","homematic_name":"w_sonne_scheint","desc":"sonne_scheint","type":"boolean","unit":"","value":false},{"name":"26","homematic_name":"w_sonne_heute","desc":"sonne_heute","type":"number","unit":"h","value":0.0},{"name":"28","homematic_name":"w_sonne_gestern","desc":"sonne_gestern","type":"number","unit":"h","value":0.0},{"name":"12","homematic_name":"w_elevation","desc":"sonne_elevation","type":"number","unit":"grad","value":-2.7},{"name":"13","homematic_name":"w_azimut","desc":"sonne_azimut","type":"number","unit":"grad","value":81.5}],"Systeminfo":{"MAC-Adresse":"9:ee:17:22:66:44","Homematic_CCU_ip":"192.168.yyy.xxx","WLAN_ssid":"meine-ssid","WLAN_Signal_dBm":-50,"sec_seit_reset":1960,"zeitpunkt":"2018-08-31 07:42:19","firmware":"weatherman_66"}}`

**Comment by t4qjXH8N** [comment]
Ich habe dein JSON mit der aktuellen Version 1.2.5 getestet und es funktioniert. Ist die IP des Wiffi in den Einstellungen des Adapters richtig eingestellt?

**Comment by Farmer-cb** [comment]
mir wurde gerade im Forum mitgeteilt, das man mit dem param:12 dem Weatherman den Port des Adapters mitteilen muss, dies habe ich nicht gemacht, habe nur param:12:1 eingetragen.

aktelle habe ich allerdings das Problem, das ich den adapter gelöscht habe und ihn neu installieren wollte, was aber leider nicht mehr geht, der Adapter wurde anscheined gelöscht, ist aber im tab-adapter immer noch vorhanden aber leider ohne löschsymbol.
lässt sich aber auch nicht mehr neu installieren, da bleibt er dan bei
`$ ./iobroker url "https://github.com/t4qjXH8N/ioBroker.wiffi-wz/tarball/master" wiffi-wz
install https://github.com/t4qjXH8N/ioBroker.wiffi-wz/tarball/master
npm install https://github.com/t4qjXH8N/ioBroker.wiffi-wz/tarball/master --production --save --prefix "/opt/iobroker" (System call)`

hängen

**Comment by t4qjXH8N** [comment]
Dieser Fehler tritt auf wenn man den Adapter aktualisieren will, die Instanz aber noch läuft. Bitte zunächst kontrollieren ob die Instanz noch läuft, wenn ja, stoppen. dann den iobroker admin neustarten mit
`
iobroker stop admin
iobroker start admin
`

Versuche dann das Update nochmal. Bitte vorher nachschauen ob die Wiffi-Instanz wirklich gestoppt ist.

**Comment by Farmer-cb** [comment]
ok
admin gestoppt
admin gestartet
kein wiffi-wz instance am laufen (im tab-adapter noch sichtbar ohne löschsymbol)
update über "installrieren über eigene URL" -> "von GitHub" -> "wiffi-wz" ausgewählt.

bleibt wieder hängen
`
$ ./iobroker url "https://github.com/t4qjXH8N/ioBroker.wiffi-wz/tarball/master" wiffi-wz
install https://github.com/t4qjXH8N/ioBroker.wiffi-wz/tarball/master
npm install https://github.com/t4qjXH8N/ioBroker.wiffi-wz/tarball/master --production --save --prefix "/opt/iobroker" (System call)
`


Auszug aus log:
`
wiffi-wz.0 | 2018-08-31 11:22:13.310 | info | Server listening on undefined:undefined
wiffi-wz.0 | 2018-08-31 11:22:13.310 | info | Opening local server on undefined:undefined
wiffi-wz.0 | 2018-08-31 11:22:13.309 | info | Opening socket ...
wiffi-wz.0 | 2018-08-31 11:22:13.307 | info | starting. Version 1.2.5 in /opt/iobroker/node_modules/iobroker.wiffi-wz, node: v6.14.3
iobroker | 2018-08-31 11:21:07.674 | info | npm install https://github.com/t4qjXH8N/ioBroker.wiffi-wz/tarball/master --production --save --prefix "/opt/iobroker" (System call)
iobroker | 2018-08-31 11:21:05.860 | info | install https://github.com/t4qjXH8N/ioBroker.wiffi-wz/tarball/master
iobroker | 2018-08-31 11:21:04.638 | info | url "https://github.com/t4qjXH8N/ioBroker.wiffi-wz/tarball/master" wiffi-wz
`

**Comment by t4qjXH8N** [comment]
Ganz ehrlich, keine Idee.

**Comment by t4qjXH8N** [comment]
Besteht das Problem auch mit anderen Adaptern von Github?

**Comment by Farmer-cb** [comment]
habs jetzt geschafft
anscheind hat sich die adapteroberfläche nur nicht aktualisiert, nach einem manuellen aktualisieren (F5) der Seite, war die installation abgeschlossen.
jetzt konnte ich die Instance installieren und meine Daten eingeben.
leider kommt jetzt die Fehlermeldung Instance allready running
nach einem iobroker stop
iobroker start geht es anscheinend, zumindest legt er die Datenpunkte an.
aber leider aktualisiert er die Daten nicht.

was muss ich denn nun mit param:12 angeben, nur die 1 oder den Port den ich im wiffi-wz eingestellt habe (standard 8181)

**Comment by Farmer-cb** [comment]
Haaaaaalt
jetzt gehts
es muss also doch param12:8181 heissen
sollte man vielleicht in der Doku erwähnen oder am besten gelich bei den einstellungen im Adapter

**Comment by Farmer-cb** [comment]
vielen Dank für die Unterstützung
