### ISSUE TITLE
Datagram error, could not find an ip!

### ISSUE THREAD

**Issue by fs-plugins** [t4qjXH8N/ioBroker.wiffi-wz#8]
es werden überhaupt keine Datenpunkte erstellt
keine Daten vom wiffi, log meldet:
Datagram error, could not find an ip!

Adapter: 2.0.0
Adapter neu installiert um alle Änderungen aktuell zu haben
Wiffi meldet: connected with CCU
wiffi-Firmware: rainyman_91 (Problem besteht mind. seit Version _87)

**Comment by t4qjXH8N** [comment]
Bitte den Adapter auf debug schalten und das Datagramm übersenden.

**Comment by fs-plugins** [comment]
Sehr gerne (ist immer noch der gleiche Fehler wie vor Wochen gemeldet…)

 

Vermutlich ist es das komische zeichen ganz am Ende…

 

2019-01-08 11:15:39.566 - debug: wiffi-wz.0 Received JSON data from Wiffi. Full message: {"modultyp":"rainyman","vars":[{"name":"0","homematic_name":"wiffi1","desc":"rainyman_ip","type":"string","unit":"","value":"xxxxx"},{"name":"1","homematic_name":"w_temperatur","desc":"aussentemperatur","type":"number","unit":"gradC","value":2.3},{"name":"21","homematic_name":"w_windchill","desc":"gefuehlte_temperatur","type":"number","unit":"gradC","value":2.3},{"name":"9","homematic_name":"w_taupunkt","desc":"taupunkt_temperatur","type":"number","unit":"gradC","value":1.3},{"name":"14","homematic_name":"w_himmeltemperatur","desc":"himmel_temperatur","type":"number","unit":"gradC","value":0.0},{"name":"2","homematic_name":"w_feuchte_rel","desc":"rel_feuchte","type":"number","unit":"%","value":93.2},{"name":"17","homematic_name":"w_feuchte_abs","desc":"abs_feuchte","type":"number","unit":"g/m3","value":5.3},{"name":"18","homematic_name":"w_regensensor_wert","desc":"regenmelderwert","type":"number","unit":"","value":9},{"name":"7","homematic_name":"w_regenmelder","desc":"regenstatus","type":"boolean","unit":"","value":false},{"name":"8","homematic_name":"w_regenstaerke","desc":"regenstaerke","type":"number","unit":"mm/h","value":0.0},{"name":"19","homematic_name":"w_regen_letzte_h","desc":"regen_pro_h","type":"number","unit":"mm","value":0.0},{"name":"20","homematic_name":"w_regen_mm_heute","desc":"regen_mm_heute","type":"number","unit":"mm","value":0.0},{"name":"32","homematic_name":"w_regenstunden_heute","desc":"regenstunden_heute","type":"number","unit":"h","value":9.8},{"name":"3","homematic_name":"w_barometer","desc":"nn_luftdruck","type":"number","unit":"mb","value":1018.22},{"name":"11","homematic_name":"w_barotrend","desc":"luftdrucktrend","type":"string","unit":"","value":"stark fallend"},{"name":"25","homematic_name":"w_bodenfeuchte","desc":"bodenfeuchte","type":"number","unit":"","value":0},{"name":"10","homematic_name":"w_lux","desc":"helligkeit","type":"number","unit":"lux","value":2050.0},{"name":"22","homematic_name":"w_sonne_diff_temp","desc":"sonnen_difftemperatur","type":"number","unit":"gradC","value":2.2},{"name":"16","homematic_name":"w_sonne_scheint","desc":"sonne_scheint","type":"boolean","unit":"","value":false},{"name":"26","homematic_name":"w_sonnenstunden_heute","desc":"Sonnenstunden_heute","type":"number","unit":"h","value":0.0},{"name":"12","homematic_name":"w_elevation","desc":"sonne_elevation","type":"number","unit":"grad","value":17.5},{"name":"13","homematic_name":"w_azimut","desc":"sonne_azimut","type":"number","unit":"grad","value":162.4},{"name":"30","homematic_name":"w_minuten_vor_sa","desc":"minuten_vor_sa","type":"number","unit":"min","value":-181},{"name":"31","homematic_name":"w_minuten_vor_su","desc":"minuten_vor_su","type":"number","unit":"min","value":327}],"Systeminfo":{"MAC-Adresse":"xxxxxx","Homematic_CCU_ip":"xxxxx","WLAN_ssid":"xxxx","WLAN_Signal_dBm":-87,"sec_seit_reset":1317,"zeitpunkt":"2019.01.08/11:15:38","firmware":"rainyman_91"}}

  _____  


 

 

MfG

Frank

 

Von: Christian Vorholt <notifications@github.com> 
Gesendet: Dienstag, 8. Januar 2019 10:52
An: t4qjXH8N/ioBroker.wiffi-wz <ioBroker.wiffi-wz@noreply.github.com>
Cc: shadowrider <plugins@fs-plugins.de>; Author <author@noreply.github.com>
Betreff: Re: [t4qjXH8N/ioBroker.wiffi-wz] Datagram error, could not find an ip! (#8)

 

Bitte den Adapter auf debug schalten und das Datagramm übersenden.

**Comment by fs-plugins** [comment]
Nachtrag:
am Ende des datagramms ist im Editor ein EOT CR LF
evtl hängt es dort?

**Comment by t4qjXH8N** [comment]
Bitte teste die Version im Branch bug-8. Bitte im Ordner iobroker.wiffi-wz den Befehl `npm i` ausführen, um neue Pakete zu installieren.

**Comment by fs-plugins** [comment]
Fehlermeldung unverändert, bin aber auch nicht sicher ob das alles so muss
(im terminal spiele ich eher nicht rum, da es ein aktives Homesystem ist...)

install-Meldungen:
$ ./iobroker url "https://github.com/t4qjXH8N/ioBroker.wiffi-wz/tree/bug-8" --debug
install https://github.com/t4qjXH8N/ioBroker.wiffi-wz/tree/bug-8/tarball/master
npm install https://github.com/t4qjXH8N/ioBroker.wiffi-wz/tree/bug-8/tarball/master --unsafe-perm --production --save --prefix "/opt/iobroker" (System call)
npm
 ERR! code E404
npm ERR! 404 Not Found: https://github.com/t4qjXH8N/ioBroker.wiffi-wz/tree/bug-8/tarball/master

auszug aus telnet:
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js                                                                           
+ npm@6.5.0                                                                                                                        
added 2 packages from 1 contributor and updated 14 packages in 22.277s                                                             
root@buanet-iobroker1:/opt/iobroker# npm install -g n                                                                              
/usr/bin/n -> /usr/lib/node_modules/n/bin/n                                                                                        
+ n@2.1.12                                                                                                                         
added 1 package from 4 contributors in 1.218s                                                                                      
root@buanet-iobroker1:/opt/iobroker# n stable                                                                                      
                                                                                                                                   
     install : node-v11.6.0                                                                                                        
       mkdir : /usr/local/n/versions/node/11.6.0                                                                                   
       fetch : https://nodejs.org/dist/v11.6.0/node-v11.6.0-linux-x64.tar.gz                                                       
######################################################################## 100,0%###########                                         
   installed : v11.6.0                                                                                                             
                                                                                                                                   
root@buanet-iobroker1:/opt/iobroker# npm -v                                                                                        
6.5.0                                                                                                           
                                                                                                                                   
npm@6.5.0 /usr/lib/node_modules/npm                                                                                                
root@buanet-iobroker1:/opt/iobroker/node_modules/iobroker.wiffi-wz# npm i                                                          
added 271 packages from 451 contributors and audited 1249 packages in 13.671s                                                      
found 5 vulnerabilities (1 low, 4 high)                                                                                            
  run `npm audit fix` to fix them, or `npm audit` for details                                                                      
root@buanet-iobroker1:/opt/iobroker/node_modules/iobroker.wiffi-wz# npm audit fix                                                  
up to date in 5.4s                                                                                                                 
fixed 0 of 5 vulnerabilities in 1249 scanned packages                                                                              
  1 package update for 5 vulns involved breaking changes                                                                           
  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)               
root@buanet-iobroker1:/opt/iobroker/node_modules/iobroker.wiffi-wz# npm audit fix --force                                          
npm WARN using --force I sure hope you know what you are doing.                                                                    
                                                                                                                                   
> fsevents@1.2.4 install /opt/iobroker/node_modules/iobroker.wiffi-wz/node_modules/fsevents                                        
> node install                                                                                                                     
                                                                                                                                   
+ gulp@4.0.0                                                                                                                       
added 195 packages from 110 contributors, removed 61 packages and updated 22 packages in 26.964s                                   
fixed 5 of 5 vulnerabilities in 1249 scanned packages                                                                              
  1 package update for 5 vulns involved breaking changes                                                                           
  (installed due to `--force` option) 

/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js                                                                           
+ npm@6.5.0                                                                                                                        
added 2 packages from 1 contributor and updated 14 packages in 22.277s                                                             
root@buanet-iobroker1:/opt/iobroker# npm install -g n                                                                              
/usr/bin/n -> /usr/lib/node_modules/n/bin/n                                                                                        
+ n@2.1.12                                                                                                                         
added 1 package from 4 contributors in 1.218s                                                                                      
root@buanet-iobroker1:/opt/iobroker# n stable                                                                                      
                                                                                                                                   
     install : node-v11.6.0                                                                                                        
       mkdir : /usr/local/n/versions/node/11.6.0                                                                                   
       fetch : https://nodejs.org/dist/v11.6.0/node-v11.6.0-linux-x64.tar.gz                                                       
######################################################################## 100,0%###########                                         
   installed : v11.6.0                                                                                                             
                                                                                                                                   
root@buanet-iobroker1:/opt/iobroker# npm -v                                                                                        
6.5.0                                                                                                           
                                                                                                                                   
npm@6.5.0 /usr/lib/node_modules/npm                                                                                                
root@buanet-iobroker1:/opt/iobroker/node_modules/iobroker.wiffi-wz# npm i                                                          
added 271 packages from 451 contributors and audited 1249 packages in 13.671s                                                      
found 5 vulnerabilities (1 low, 4 high)                                                                                            
  run `npm audit fix` to fix them, or `npm audit` for details                                                                      
root@buanet-iobroker1:/opt/iobroker/node_modules/iobroker.wiffi-wz# npm audit fix                                                  
up to date in 5.4s                                                                                                                 
fixed 0 of 5 vulnerabilities in 1249 scanned packages                                                                              
  1 package update for 5 vulns involved breaking changes                                                                           
  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)               
root@buanet-iobroker1:/opt/iobroker/node_modules/iobroker.wiffi-wz# npm audit fix --force                                          
npm WARN using --force I sure hope you know what you are doing.                                                                    
                                                                                                                                   
> fsevents@1.2.4 install /opt/iobroker/node_modules/iobroker.wiffi-wz/node_modules/fsevents                                        
> node install                                                                                                                     
                                                                                                                                   
+ gulp@4.0.0                                                                                                                       
added 195 packages from 110 contributors, removed 61 packages and updated 22 packages in 26.964s                                   
fixed 5 of 5 vulnerabilities in 1249 scanned packages                                                                              
  1 package update for 5 vulns involved breaking changes                                                                           
  (installed due to `--force` option) 
root@buanet-iobroker1:/opt/iobroker# cd /opt/iobroker/node_modules/iobroker.wiffi-wz                                               
root@buanet-iobroker1:/opt/iobroker/node_modules/iobroker.wiffi-wz# npm i                                                          
audited 6512 packages in 10.345s                                                                                                   
found 0 vulnerabilities 

Neustart der docker-instanz danach habe ich auch versucht

**Comment by t4qjXH8N** [comment]
Danke fürs versuchen. Wenn der ioBroker-Translator wieder funktioniert spiele ich den Patch in den Master-Zweig ein.

Falls Du es nochmal probieren willst, ersetze die main.js mit der main.js aus dem Patch Zweig. Dann muss man aber npm i ausführen um das underscore Paket zu installieren.

**Comment by fs-plugins** [comment]
ne ich möchte nicht - aber wie willst du MIR helfen ohne Infos ;-)

es funzt !!!!

**Comment by t4qjXH8N** [comment]
Der Fehler ist in Version 2.0.1 behoben.
